skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
stablecoin_q3_2026 = "GyS3h3kXEHADYhzHXR2r9VBMYejFNeGwg7Ln66v2bqo5"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
